# Generated by Django 5.1 on 2024-08-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebinapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bin',
            name='paste_expiration',
            field=models.CharField(choices=[('NO', 'Never'), ('BU', 'Burst after read'), ('10M', '10 Minutes'), ('1H', '1 Hour'), ('1D', '1 Day'), ('1W', '1 Week'), ('2W', '2 Week'), ('1M', '1 Month'), ('6M', '6 Month'), ('1Y', '1 Year')], default='NO', max_length=3),
        ),
    ]
