# Generated by Django 5.1 on 2024-08-30 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pastebinapp', '0002_bin_paste_expiration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bin',
            new_name='PasteBin',
        ),
    ]
