# Generated by Django 5.1 on 2024-09-02 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebinapp', '0003_rename_bin_pastebin'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastebin',
            name='expire_at',
            field=models.DateTimeField(default=datetime.datetime(2124, 8, 9, 16, 42, 23, 682908)),
        ),
        migrations.AddField(
            model_name='pastebin',
            name='hit_count',
            field=models.IntegerField(default=0),
        ),
    ]
