# Generated by Django 5.1 on 2024-09-03 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebinapp', '0004_pastebin_expire_at_pastebin_hit_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastebin',
            name='paste_exposure',
            field=models.CharField(choices=[('public', 'Public'), ('unlisted', 'Unlisted')], default='public', max_length=8),
        ),
        migrations.AddField(
            model_name='pastebin',
            name='title',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='pastebin',
            name='expire_at',
            field=models.DateTimeField(default=datetime.datetime(2124, 8, 10, 11, 54, 42, 946192)),
        ),
    ]
