# Generated by Django 5.1 on 2024-09-04 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebinapp', '0005_pastebin_paste_exposure_pastebin_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastebin',
            name='is_password_protected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pastebin',
            name='password_hash',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='pastebin',
            name='expire_at',
            field=models.DateTimeField(default=datetime.datetime(2124, 8, 11, 17, 33, 50, 141316)),
        ),
    ]
