# Generated by Django 5.1 on 2024-09-06 10:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebinapp', '0006_pastebin_is_password_protected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastebin',
            name='expire_at',
            field=models.DateTimeField(default=datetime.datetime(2124, 8, 13, 10, 13, 4, 756993)),
        ),
        migrations.AlterField(
            model_name='pastebin',
            name='password_hash',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
