# Generated by Django 5.1 on 2024-09-11 05:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebinapp', '0008_alter_pastebin_expire_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pastebin',
            name='password_hash',
        ),
        migrations.AlterField(
            model_name='pastebin',
            name='expire_at',
            field=models.DateTimeField(default=datetime.datetime(2124, 8, 18, 5, 21, 30, 419441)),
        ),
    ]
