# Generated by Django 5.1 on 2024-09-11 05:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebinapp', '0009_remove_pastebin_password_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastebin',
            name='password_hash',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='pastebin',
            name='expire_at',
            field=models.DateTimeField(default=datetime.datetime(2124, 8, 18, 5, 22, 32, 402775)),
        ),
    ]
