# Generated by Django 5.1 on 2024-09-11 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebinapp', '0010_pastebin_password_hash_alter_pastebin_expire_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastebin',
            name='expire_at',
            field=models.DateTimeField(default=datetime.datetime(2124, 8, 18, 15, 54, 57, 227317)),
        ),
        migrations.AlterField(
            model_name='pastebin',
            name='password_hash',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
